### ISSUE TITLE
Remove -e backup files created by sed on macOS

### ISSUE THREAD

**Issue by hillelcoren** [hillelcoren/flutter-redux-starter#12]

**Comment by danibjor** [comment]
`starter.sh` have a `cleanup` switch for cleaning up temp-files

**Comment by gentlefox** [comment]
On OSX `sed -i` expects a file extension.
Thus when `sed -i -e "s/stub/$module/g" "$filename.dart"` is called, it creates a backup using the next argument "-e".

The fix: `sed -i '' -e "s/stub/$module/g" "$filename.dart"` assigning an empty string as the extension parameter.

**Comment by hillelcoren** [comment]
I think I tried that, I believe adding '' causes problems on Windows or Linux

**Comment by gentlefox** [comment]
Yeah, I've been seeing that. The cleanup script is a nice workaround.

I've been working with the PR that Julian Paraian submitted, trying to get the shell scripting to be cross-platform. Progress would have been faster with the inclusion of code comments...

The amount of time I've been able to focus on it looks to be reduced for a while as it appears we have to stop using Flutter for the current project (for now) meaning the rush job of creating it anew in another format.

I'll still see what I can do towards contributing to the amazing work you're doing here - thank you for your contribution!
