### ISSUE TITLE
XXX has stoped

### ISSUE THREAD

**Issue by jiangzhixiao** [hillelcoren/flutter-redux-starter#15]
@hillelcoren ,hi hillelcoren,when i follow your example command,i got the error when install apk to emulator 
![image](https://user-images.githubusercontent.com/7273487/42917112-c712d3de-8b3a-11e8-9150-c607336b6f22.png)

but flutter mobile runs well 
![image](https://user-images.githubusercontent.com/7273487/42917272-71d61cd6-8b3b-11e8-8e94-499f4c94fa95.png)

can you give some advice?

**Comment by jiangzhixiao** [comment]
i have found the problem.The MainActivity.java was generated in this package:
![image](https://user-images.githubusercontent.com/7273487/42919982-2190d67e-8b47-11e8-9e25-f568f3c23d01.png)
 the mwh folder is empty ...
In the MainActivity.java 
![image](https://user-images.githubusercontent.com/7273487/42919999-355cbc86-8b47-11e8-89c9-9e816e6a8da0.png)

how to fix this?

**Comment by jiangzhixiao** [comment]
ok ,i resolve it .

**Comment by hillelcoren** [comment]
Glad to hear you figured it out, what was the issue?

The MainActivity.java file should have been corrected when running the init command.

**Comment by jiangzhixiao** [comment]
@hillelcoren it's my mistake,i excute the wrong command :(, by the way ,how to set the login screen as default ???

**Comment by hillelcoren** [comment]
You need to change the routes and make sure the login route is the only one set to '/'.

**Comment by jiangzhixiao** [comment]
@hillelcoren ,I have been studying redux for a about 2 days, At first, I was confused about the new concept,Store,StoreProvider,StoreConnector....but Suddenly I found it very similar to mate(a tab based event driven flex framework),so the idea of learning is clear to me.

**Comment by jiangzhixiao** [comment]
@hillelcoren ,hillelcoren,i look into flutter-mobile, the  route '/' is in init_screen.dart,that means the init_screen was loaded first .then in the onInit method,it fires the LoadStateRequest action, how this LoadStateRequest  action trigger the LoginView???

**Comment by hillelcoren** [comment]
Flutter automatically loads the route named '/'

**Comment by jiangzhixiao** [comment]
@hillelcoren but the LoginScreen 's route is '/login', as you say, flutter loads route '/' default. it means flutter automatically loads InitScreen,not LoginScreen. 
![image](https://user-images.githubusercontent.com/7273487/42935977-8b6534ec-8b7d-11e8-904d-b981f15a48c9.png)
![image](https://user-images.githubusercontent.com/7273487/42935987-8fa7934c-8b7d-11e8-9805-ec78612c969b.png)

what happend between InitScreen and LoginScreen, thanks for  your patience

**Comment by hillelcoren** [comment]
Sorry my mistake, here's where the login screen is shown.

https://github.com/hillelcoren/flutter-redux-starter/blob/master/lib/redux/auth/auth_middleware.dart#L32
