### ISSUE TITLE
SocketException: OS Error: Connection refused, errno = 111, address = localhost, port = 35779

### ISSUE THREAD

**Issue by jiangzhixiao** [hillelcoren/flutter-redux-starter#16]
hi @hillelcoren , i create a spring boot backend, then use this starter,everything is ok ,but when i debug the app, the console print below log:
 `[INFO] LoggingMiddleware: {Action: LoadPrescsFailure{error: SocketException: OS Error: Connection refused, errno = 111, address = localhost, port = 35818}, State: AppState {`
and the screen is stuck in here
![image](https://user-images.githubusercontent.com/7273487/43309831-72a54230-91b8-11e8-857a-ab5aca8a06a9.png)
  by the way, i used JWT,   is that possible caused by this?? 
   i need to log in first???
   thank you for taking time to help me on this problem.

**Comment by hillelcoren** [comment]
I'm not sure... a comment [here](https://stackoverflow.com/questions/50369768/flutter-http-error-socketexception-os-error-connection-refused) suggests adding an "accept:application/json" header may help.

The relevant code is here: https://github.com/hillelcoren/flutter-redux-starter/blob/master/lib/data/web_client.dart#L10

You may also want to try using telnet to confirm you can connect to the host/port.

**Comment by jiangzhixiao** [comment]
@hillelcoren, a big mistake... i set kApiUrl='localhost:8888/api',the problem is "localhost"
actually "localhost" should be replaced to "10.0.2.2"
  If you run AVD(Client)/spring boot(Server)   ,in same computer， you have to set the kApiUrl to "10.0.2.2:port/api"
 thanks again !

**Comment by hillelcoren** [comment]
Glad to hear it's working, thanks for sharing the fix!

**Comment by ricardocrescenti** [comment]
I replaced 'localhost' with my notebook's IP and released the port used in the firewall

**Comment by kuyu132** [comment]
under mac you need set the ip 0.0.0.0, then mac will show the firewall dialog, press agree, then you can access the mock server in your LAN

**Comment by josed1608** [comment]
Hey, I've been trying to connect to connect to my Spring WebSockets (they use STOMP) but when i try to connect with IOWebSocketChannel I get the exception:
WebSocketChannelException: WebSocketChannelException: WebSocketException: Connection to 'http://10.1.137.147:8080/ws#' was not upgraded to websocket

Did you encounter this issue?

**Comment by hillelcoren** [comment]
Maybe the info here will help... https://github.com/flutter/flutter/issues/11444

**Comment by josed1608** [comment]
Just found the problem. Turns out the the sockJs configuration on the Spring STOMP endpoint caused the http upgrade request made by Flutter to not match the expected format on the server side. My server has to work for both an Angular web app and a Flutter mobile app so I guess I'll just have two websocket endpoints, one for web and the other for mobile. I was also missing a 0 byte at the end of the body of the STOMP frame, so that was also messing things up.

Thanks for the reference to the issue, it helped a lot in diagnosing the problem.

**Comment by hillelcoren** [comment]
Thanks for sharing the solution!

**Comment by YuanTianyang** [comment]
> I replaced 'localhost' with my notebook's IP and released the port used in the firewall

You are so good!

**Comment by caseyryan** [comment]
None of the comments above is the solvation for this problem. I'm trying to do a get request like this: 
```dart 
http.get('https://localhost:5000/api/Users/CheckFirebaseToken?IdToken=myTokenHere');
```

And it throws exactly the same error. But when I do the same request from postman it works like a charm

**Comment by julianrodri11** [comment]
En mi caso tenia montado mi pagina web en wordpress de forma local con xampp, para consumir la api rest de wordpress con flutter, además mire este vídeo, muy bueno:

https://www.youtube.com/watch?v=IaNOJD07aKU&t=26s.

Pero tuve que detener cuando me salio el 
errno 111: aparecía el error por colocar localhost o 127.0.0.1 en la http, estaba diciendo que la pagina web estaba montada en el celular cuando la aplicación se abría, y no era así por que el servicio estaba en el pc, entonces debía sacar la ip por donde el pc tenia internet en mi caso por wifi, y colocar esa ip, ademas si se tenia un puerto diferente habilitar la entrada y salida por las reglas de firewall.
`final respuesta = await http.get(
      'http://127.0.0.1:90/word/wp-json/wp/v2/pages?_embed',
      headers: {"Accept": "application/json"});`

Antes de eso me cruce con el errno 7: se debía a que celular no tenia activado el wifi además debían estar conectado a la misma red wifi tanto el portátil como el celular.

Al final:
El celular y el portátil debían estar en el mismo wifi
Desde el portátil se debía crear una regla de firewall de entrada y salida en mi caso por el puerto 90
Se debía verificar desde el navegador del celular, que se pudiera acceder al servicio api rest local montado en wordpress asi: 
`http://192.168.0.104:90/word/wp-json/wp/v2/pages?_embed`
Si había respuesta entonces se iba a mostrar los parámetros solicitados cuando se corra la aplicación en el celular.

Mas fácil aun era usar un api rest wordpress publico o con ip publica como este:
https://virtuooza.com/wp-json/wp/v2/posts?_embed
para ver si la aplicación que se desarrollo en el vídeo funcionaba correctamente para hacer pruebas y así luego consumir nuestros propios servicios.

Código final.
`import 'package:http/http.dart' as http;
import 'dart:convert';

Future<List> fetchWpPosts() async {
  final respuesta = await http.get(
      \'http://192.168.0.104:90/word/wp-json/wp/v2/pages?_embed  \',
      headers: {"Accept": "application/json"});
  var datosConvertidosJson = jsonDecode(respuesta.body);
  return datosConvertidosJson;
}
`

**Comment by 0xjoaovictor** [comment]
> @hillelcoren, a big mistake... i set kApiUrl='localhost:8888/api',the problem is "localhost"
> actually "localhost" should be replaced to "10.0.2.2"
> If you run AVD(Client)/spring boot(Server) ,in same computer， you have to set the kApiUrl to "10.0.2.2:port/api"
> thanks again !

Thank you!!!!!!!!!!!!!!!!!!!!!

**Comment by mejorgabriel** [comment]
I ran under the same error. In my case, the problem was that the android emulator I was using didn't have the option to connect to WiFi. It could use internet, I could call internet servers, but when trying to connect to 10.0.2.2, I always got that error.
The solution was to **change the emulator and use a newer version**, as WiFi could't be enabled in the version I was using. That way I could connect to my local server.

**Comment by hawarih** [comment]
Dear I have this problem in my flutter app - when connect strapi with mongodb
SocketException: OS Error: Connection refused, errno = 111, address = localhost, port = 44128

this is my code for registerpage
```
 http.Response response = await http.post(
      'http://localhost:1337/auth/local/register',
     body:{"username": _username, "email": _email, "password": _password});

     final responseData = json.decode(response.body);
     setState(() => _isSubmitting = true);
     _showSuccessSnack();
     _redirectUser();
     print(responseData);
   } 
```
any one have idea how to solve this

**Comment by sagarshende23** [comment]
> Dear I have this problem in my flutter app - when connect strapi with mongodb
> SocketException: OS Error: Connection refused, errno = 111, address = localhost, port = 44128
> 
> this is my code for registerpage
> 
> ```
>  http.Response response = await http.post(
>       'http://localhost:1337/auth/local/register',
>      body:{"username": _username, "email": _email, "password": _password});
> 
>      final responseData = json.decode(response.body);
>      setState(() => _isSubmitting = true);
>      _showSuccessSnack();
>      _redirectUser();
>      print(responseData);
>    } 
> ```
> 
> any one have idea how to solve this

Found the Solution: If you're running the server locally and using the Android emulator, then your server endpoint should be 10.0.2.2:8000 instead of localhost:8000 as AVD uses 10.0.2.2 as an alias to your host loopback interface (i.e) localhost

`**'http://10.0.2.2:1337/auth/local/register',**`

clear explanation checkout this Answer:

[stackoverflow.com/questions/60001536/flutter-socketexception-socketexception-os-error-connection-refused-errno](https://stackoverflow.com/questions/55785581/socketexception-os-error-connection-refused-errno-111-in-flutter-using-djan)

**Comment by Chaitanyaha** [comment]
What should be the host link if I want to run the application on my physical phone?
Also how would things work if I upload the application on google play store what would be the host link then?

**Comment by sagarshende23** [comment]
> What should be the host link if I want to run the application on my physical phone?
> Also how would things work if I upload the application on google play store what would be the host link then?
yeah the Same Question comes to my mind right Now!!!

**Comment by Chaitanyaha** [comment]
If you have the answers in near future then please answer this Question here...!

**Comment by Majid110** [comment]
You can forward 8888 port from AVD to host computer by running this command:
adb reverse tcp:8888 tcp:8888

and now localhost:8888 is accessible.

Also that port (8888) must allowed in firewall Inbound Rules.

**Comment by emmanuelNono** [comment]
@hillelcoren  , une grosse erreur ... j'ai mis kApiUrl = 'localhost: 8888 / api', le problème est "localhost" en
fait "localhost" devrait être remplacé par "10.0.2.2"
Si vous exécutez AVD (Client) / spring boot (Serveur), dans le même ordinateur, vous devez régler le kApiUrl sur "10.0.2.2:port/api"

tu es génial

**Comment by macelux** [comment]
> What should be the host link if I want to run the application on my physical phone?
> Also how would things work if I upload the application on google play store what would be the host link then?

Any solution to this?

**Comment by MuhammadNizamani** [comment]
> @hillelcoren, a big mistake... i set kApiUrl='localhost:8888/api',the problem is "localhost"
> actually "localhost" should be replaced to "10.0.2.2"
> If you run AVD(Client)/spring boot(Server) ,in same computer， you have to set the kApiUrl to "10.0.2.2:port/api"
> thanks again !

how can I change localhost to 10.0.0.2

**Comment by MuhammadNizamani** [comment]
I am using Genymotion and i am trying to connect flutter with python through flask but when I run my app and send a request to API I got a connection refused error. kindly help how to solve the problem.

**Comment by caseyryan** [comment]
> @hillelcoren, a big mistake... i set kApiUrl='localhost:8888/api',the problem is "localhost"
> actually "localhost" should be replaced to "10.0.2.2"
> If you run AVD(Client)/spring boot(Server) ,in same computer， you have to set the kApiUrl to "10.0.2.2:port/api"
> thanks again !

You don't even know how much nerves your reply saved me :D I wish you a great day!

**Comment by Urvish24** [comment]
If you done all thing perfect then try to put some delay to call the fuction 
It Work Perfect for me

**Comment by okinawaa** [comment]
> @hillelcoren, a big mistake... i set kApiUrl='localhost:8888/api',the problem is "localhost" actually "localhost" should be replaced to "10.0.2.2" If you run AVD(Client)/spring boot(Server) ,in same computer， you have to set the kApiUrl to "10.0.2.2:port/api" thanks again !

you save my life

**Comment by IncognitoGK9** [comment]
Exception has occurred.
SocketException (SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = localhost, port = 44198) for using real device with emulator. On the configuration, I have passed the actual ip address of the host (192.168.43.81 which is in the same wi-fi network with the actual real device on iP: 192.168.43.1 and on the firebase json file, am using 0.0.0.0 to have full broadcast. 

NOTE: this is flutter + Dart + firebase emulators + Real device (on others, android emulator, or web, it is working fine) - I need to use real device.

What could be wrong?

**Comment by EufranioDiogo** [comment]
We(myself and my girlfriend) was running a Android Phone (Not emulator) and we was using a WebService on our local server on the same network with Android Phone, but the error was in the port of our local server, it was not open.

In our local server running Ubuntu 22.04.2 LTS.

`sudo ufw allow <SERVER_PORT>`

You can search how to open a port in your OS and see if it works for you.

for Linux:
https://www.digitalocean.com/community/tutorials/opening-a-port-on-linux#for-ubuntu-users-and-ufw-based-systems

for MacOS:https://www.macworld.com/article/671729/mac-firewall-how-to-open-specific-ports-in-os-x-10-10-firewall.html

for Windows:
https://learn.microsoft.com/en-us/sql/reporting-services/report-server/configure-a-firewall-for-report-server-access?view=sql-server-ver16
