### ISSUE TITLE
Invalid argument(s): Unknown type on deserialization. Need either specifiedType or discriminator field

### ISSUE THREAD

**Issue by jiangzhixiao** [hillelcoren/flutter-redux-starter#17]
@hillelcoren ,i'm using java backend, when i post a login request to the backend,

**i got the response:**

 `{data: {accounts: [], version: 5.4, token: null, static: {}}, error: null}`

 **when excute at this line(endities.g.dart line 237)**:
  ``` dart 
    result.data.replace(serializers.deserialize(value,
                  specifiedType: const FullType(LoginResponseData))
              as LoginResponseData);
  ```

**i got the error**

  `I/flutter (11099): Deserializing '[data, {accounts: [], version: 5.4, token: null, static: {}}, null, null]' to 'LoginResponse' failed due to: Invalid argument(s): Unknown type on deserialization. Need either specifiedType or discriminator field.`

`E/flutter (11099): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:`
`E/flutter (11099): type 'DeserializationError' is not a subtype of type 'String'`
 
i have searched by google, still don't quite clear..would you please give me some tips ? thanks hillelcoren.

**Comment by hillelcoren** [comment]
I'd suggest manually checking the sample response can be deserialized.

**Comment by jiangzhixiao** [comment]
@hillelcoren  sorry ,using the flutter-mobile,not the flutter-redux-starter...

**Comment by hillelcoren** [comment]
You may want to close this issue and open a new one.

What do you mean by 'java backend'?

**Comment by jiangzhixiao** [comment]
it means my server side code is using java(spring boot ),not the invoice-ninja(PHP).
can i open the issue in flutter-mobile repository ?

**Comment by hillelcoren** [comment]
Are you trying to use the Invoice Ninja mobile app with a different invoicing platform? 

I'm sorry, I wouldn't be able to help (and please be sure to follow the license).

**Comment by jiangzhixiao** [comment]
no,not another invoiceing platform,just a java & flutter demo ,i'm studing flutter.

![image](https://user-images.githubusercontent.com/7273487/43636663-4f6f1c18-9745-11e8-824c-855516be778f.png)

**Comment by hillelcoren** [comment]
I'm sorry, the Invoice Ninja mobile app is only designed to be used with the Invoice Ninja web app. 

I'd suggest using the redux starter to make an app rather than the use the invoicing app.

**Comment by jiangzhixiao** [comment]
ok, thanks hillelcoren, i change to use redux-stater
