### ISSUE TITLE
Couldn't clone hacker_news or posts

### ISSUE THREAD

**Issue by parthvora25** [hillelcoren/flutter-redux-starter#34]
F:\Flutter Projects>git clone git@github.com:hillelcoren/flutter-redux-starter.git hacker_news && cd hacker_news
Cloning into 'hacker_news'...
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

F:\Flutter Projects>git clone git@github.com:hillelcoren/flutter-redux-starter.git posts && cd posts
Cloning into 'posts'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Also add one list of the <applications> in the readme file so that anyone can use those publicly available apps to clone with redux flutter and make sure to update them as well from time to time. Thanks!!!

**Comment by hillelcoren** [comment]
I'm not sure, it's a public repo?

Maybe this will help:

https://help.github.com/en/articles/testing-your-ssh-connection

**Comment by parthvora25** [comment]
Thanks i solved it. 
Using https instead of ssh git clone and http will only work.
You can share this thing in your readme file.
